# Generated by Django 3.1.6 on 2021-02-28 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('tasks', '0001_initial'), ('tasks', '0002_auto_20210214_1539'), ('tasks', '0003_auto_20210216_1104'), ('tasks', '0004_auto_20210218_1543'), ('tasks', '0005_auto_20210224_1757'), ('tasks', '0006_auto_20210228_0129')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_date', models.DateField(null=True)),
                ('deadline', models.DateField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('pushed_on_portal', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'NEW'), ('in_progress', 'IN_PROGRESS'), ('ready_to_review', 'READY_TO_REVIEW'), ('ready_to_upload', 'READY_TO_UPLOAD'), ('cancelled', 'CANCELLED'), ('uploaded', 'UPLOADED')], default='new', max_length=20)),
                ('given_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='given_by', to=settings.AUTH_USER_MODEL)),
                ('given_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='given_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('regular_price', models.FloatField(blank=True, null=True)),
                ('sale_price', models.FloatField(blank=True, null=True)),
                ('curr_price', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('not_reviewed', 'NOT_REVIEWED'), ('approved', 'APPROVED'), ('rejected', 'REJECTED'), ('uploaded', 'UPLOADED')], default='not_reviewed', max_length=20)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('last_mod_onsite', models.DateTimeField(blank=True, null=True)),
                ('last_modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
                ('axiom_price', models.FloatField(blank=True, null=True)),
                ('carrefour_price', models.FloatField(blank=True, null=True)),
                ('jumbo_price', models.FloatField(blank=True, null=True)),
                ('lulu_price', models.FloatField(blank=True, null=True)),
                ('new_reg_price', models.FloatField(blank=True, null=True)),
                ('sharaf_dg_price', models.FloatField(blank=True, null=True)),
                ('suggested_price', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
