# Generated by Django 3.1.6 on 2021-02-28 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_squashed_0006_auto_20210228_0129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='curr_price',
        ),
    ]
