# Generated by Django 3.1.6 on 2021-03-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_product_curr_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='parent_id',
            field=models.IntegerField(default=0),
        ),
    ]
