# Generated by Django 3.1.6 on 2021-03-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_product_parent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='permalink',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
