# Generated by Django 3.1.6 on 2021-03-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_product_permalink'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='axiom_product_link',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='carrefour_product_link',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='jumbo_product_link',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='lulu_product_link',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sharad_dg_product_link',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
