# Generated by Django 3.1.6 on 2021-03-07 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20210307_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sharad_dg_product_link',
            new_name='sharaf_dg_product_link',
        ),
    ]
